apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: calibre
spec:
    secretTemplates:
        - name: restic-calibre
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:A1CxvwqpzEADa0O3IHtS0S6//xKDGttn/EUv71eWmnk0FYBxVow51OQR1zkvPUj/AN9AhciTcw==,iv:RIGql1a/bmvpCHHbSrA7s4zlGi52QxR9YyZseQu/Huw=,tag:GH6OYWBEg+ANON2ur1Y2CQ==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:QIsDXYg40xSkDG5XuvrG5l0gI/g=,iv:oKVF4IkfqNZJdEqY4gJ54LOXZntn0E2zqN0+o3mjfr4=,tag:QRvg9y1jHTVl+y4PDg3uPQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WS6KrnQm83REw9Oy3VSpFKXQicE=,iv:33ENbLjjXDnf8145NY1/TdO28xWSYD0kVVAno/uKBZI=,tag:Z4GEl01ptKkY8ZT2xWbIyw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SKelMw9QjMh0BRcq/+xwgLK720LwJDDHh/JQht3bzWPVaHXh,iv:sCmkSFsWPJGEnPZw0xhmaG8MaYlp+d2Xcze3rukz410=,tag:Pk3QMdXkLcD2PAZeY+V8rg==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRU9SWmx5SGNGOEtlV2ZF
            S2VEaTVseVZ0SWFYWlgzUlRKMk4zZDRId0g4Ci9sRFlnOG9sdmpWK2VSQjdMQlRu
            cFpDNUwzWUJuVlVZSTdndk44Wk4zalkKLS0tIEM2OXkxay9IRVdqOW1HTzRxL2lN
            NGo3U2Vjamh4cnZ2d2JZWUhJeWtpMzAKJj1iWZbRFNuif0u9NqlhI8650Y1vP/m8
            E8vSMCrVMD9UMCfdf3p1Zr321iBAVwbyE2a4Jq76bZVmMzgoYraSlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T05:58:01Z"
    mac: ENC[AES256_GCM,data:5kP313wJnhQWGkXenRHjdxJpCyNBPRvkOGAtfXhqbYsxelBTMEgEAxuLp+fRjdUU7crKjjJsLMC2iVM0AD0IiR70VCc9vvZeeadxWRIVC9UoG5Drm8ooFDXKSaPFVRBTXpZfpzEGVHmNccvzJrJ06Ns1AgmBEmNcdxNHIAoqecE=,iv:FOZhgieTpdR3Nnc6Cfyd3yM3XOJLPQ9d3q7IV/oSCDU=,tag:KF/fCrTcexzZ/fUHrLuyJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
