apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: calibre
spec:
    secretTemplates:
        - name: restic-calibre
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:eUERejncfn+LFj/SV+gVbZHd1LavtevhF2AZesu8Q4ZTRO1TKfqRWJLE5+3aScoljmgCasgIWmzDdZ9Je70=,iv:FdoeF+6YgSR6ZWwxmdK1apz12i0P+urQdJYFdn1EUJ0=,tag:AM/nesIynygKi/lH/6/aTg==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:18DV+TO2ddLi/um+X/o0vuRfoIs=,iv:KwYKwQ7cMg8GdCTPbSZTWVXrJUjoLSh1liX254n3m8I=,tag:hNRd5DrK/bzPD4Yd6ZKWTg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+tdwl8FmbF+i2u5S7PoN+pqZ+F0=,iv:S2C1lWZTY7ncBLnvFWN5p8pTLpWE2ikHpSttv7G5QvM=,tag:K4eFSFu3fW9XYDgw+KCOag==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4CLQKNP4XlM7hEnKOzD3Q5jmajOKVw1Xx+wn7rDa0EWuKhah,iv:V6yKUjWDguMdGmIN1vxYJu4MfICdqOzFofNALGhlZYk=,tag:2pgbYOsTgTSXNf22alBT5g==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSkJJbGlNMHF1U3dZblJo
            Y29PQ2pwZWFvc3dqN2F3dVl6SVlEQ3plYWp3Cm5OWk92eXNUcmJMNUJpNmZyTGlX
            cVlITmZKZzhmOU4xVlByaEhsaFVIRlUKLS0tIHgwdjdpcCsvVXN2SU93OHlnUFNE
            QnJod1UxSkVicXdFcFcyeG9CU1B5dHcKszKy03KCIbt5HmMldAAyvj/xPN/oxd4m
            9w/F3ryjT3rOcBj7Zul1/wi/3OTyrHaaZaNdwqeekTNOraNDIWLG6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T08:43:38Z"
    mac: ENC[AES256_GCM,data:QsIhAJizgQsfdu+VI/3dtjbC9d/vl5/Nzt9m+RLQLzHCfYQ1C1ZDR0zPNn6o40dY64s4zYoJwkp7XeitGycrZ2HEJQSoPlZiHEwg6sX6Z+gS3zXXuMaw9JlSyE22wjK3aH4XZmrfcjl/f9u7fxNXYai9lvZ5QRSfh5rb4E4lT+g=,iv:ObIbqyp7ncwjiJdWAjjoc6QrHYYXjd/5RHAQksA7i7w=,tag:FZQ2mHuFoW5+fGJNNw/kpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
