apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ersatztv
spec:
    secretTemplates:
        - name: restic-ersatztv
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:9kFTzgHh//MY0UBPgwcqCDDItmy+fyFzanKoPZoCjI7hOWsiyCbSB3YqMeHvCpWV55NbSpF51bk=,iv:YQgfGH5tP3aJD9lLKf6DUo9ajZ0obuI9OJNgZZ93g+Q=,tag:DxyTpVdI8yVbh+9Iidm67g==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:4Ut1Rks31hp/kn3Dz6SO6n7Usvo=,iv:df1xAE/vOxWl3+bf4S9qZvfGtzXg+aE3HuYDDqghFkk=,tag:qgiqMxjErbuXogwtpjKq7g==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KNlePJ2YZvaf9k14ytxAR4MidXc=,iv:ijEdGNFg9CBwvLFcqqwiQGFeNC0xB6Yn13BUHzDxfM0=,tag:pxKD4ByIUAWK+beCuHYxIA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HH8eFIk33M19eDt6zwnbyVEP5sGzeqLcq7r+t8qoctjGgGDB,iv:IZ1m+WinyAg9BlB7QRMfAk1joQAytyjoqA5qhdszUoE=,tag:c0t4W20B6HW3hgGgoIG3XA==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoclZJZjhVTStrNW1tQ3g4
            N29QbFd2UFMrWWJEK3FhZ04rSkZtcW82L1VZCm5TeUFXOFRFN2VSeGRLNnY1NExo
            OUl2ZmlpMnZpSGJEeHJJdVMvZzg3QzgKLS0tIERjQ3QwMXZXZlNwKzFwQmJOdWNY
            NkVGb2tsNzk3eDVTVnBSY3hGUTJxdzQKven0i3joC5F69jj/xTACoTOP0tH76iAi
            UJZ0NJnD3pRdMZdvwh2Hex8wa4smdbKP3NH1Ud7i9JRT3y0wOCMdQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T23:08:53Z"
    mac: ENC[AES256_GCM,data:aVEmPj7GCKjf8+P3KtoK1h430C7VwBHn71h53yVJoN/TTA3fXMDWmlVubfxo+TZPU/wMiW72fwtckQXeiEjv1q3tI4sU2aaoB/OGuGE6knWT2Ut0lLMmKcVI5FQBvuRsgyNIEXB5zktB5NVeNfGa0DGnF+woYMkIIXW8eHS/G0Y=,iv:+z6vLqF3hUALsWvG16lag38W86iOjm7OvkxqGY1+yNQ=,tag:ixP3ddlKT/bvg2GU3gKpZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
