apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: omada-controller
spec:
    secretTemplates:
        - name: restic-omada-controller
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:sqING1dBxxTklAARsZeCv9GKC6DCBfPZPVV1kX6YKESXqmXHGpmkQBn9skug/MCyYPqeJz480Fa+kVMUTIk403nFxFgJvd0=,iv:aXQ6tlSRi0hS1lLFMpJnVnhFZ3cf31Foiko2N6/V5ec=,tag:Vz58jwVfOObwXTC6LNIZJw==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:XhA4xyccTKr4fnCc+K3Gg0Em0Jk=,iv:5FzqNjTtRaTAgyWcrVZfucG0en7r6J8BzevGRTmESF4=,tag:lOKVhP2htATMnqaBXj7gaQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:l6aRjpOHnS6Gqi3HT4P1d+/IRDE=,iv:drnrxGIp8jVwMJTlxT3XE8jK/OOXH74fgDr47nIxOrU=,tag:2V3wLa1Go38r1houjReK/w==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RHJMU4gZK56JVL62B5qNaNB5gYIthySMdQEeNRx7yYOsGZkC,iv:fSnpfr/hjf4Xt4Bam1iAa4BRch2FtpW/IhfrIPxCB04=,tag:p9/xEIhHqkRQg7yk5lszdw==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRGptUnZYVXZlSWZIRHNX
            S1ZVcWEyTHdWbmJURzhEeDVSakx1V0VGTmdnCmdmeHVORVNYbkl0RldFYkV2Vld5
            d1JEZk94ejFid040TlQrNlJXVytHVlUKLS0tIEJscjBRVlBmZi9zUjJMQ2xKR2xW
            azdtdUllai9CejhScGJ2WjlVVGF6UmsKytEz/8wOPldhuTIafe71GUomyLyiwHeT
            ot5H3WPl4dZVEzTRHHqL3HvVri43YkJUNU1Id6OdbFgIwv5ar+6DAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T14:53:29Z"
    mac: ENC[AES256_GCM,data:808exFY44sQu3EGN0aP1+7y6qT5OAMTeUpbmOzi7xePRrfBnc22uRwP9SpKH61w26GkTmdb2XW5hiGthx+QL1JANcsDIWlWDG6mE9V72fSAQub7+b+IEfCxnj0OBvd+eMlYC01DcZpYxTo18xdLxpH7zG6Sk19G1vGTs9jwuobs=,iv:fQfbaNDIeweuQOMuPN/duGGWVWrztumOg4l1Jd+/5OE=,tag:hpakJmG5gVXv8OaBViiIzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
