apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent
spec:
    secretTemplates:
        - name: restic-qbittorrent
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:odQFpW/FLGfStwocOsSOuuMeETFb6qqbY3vn5XqcaM7hmOxHb1oyCd3Y/qe20y6nYQmklUzUcwuM6fpFpEyvU1CD,iv:rZRb0LB+VKdW/h+VBJTaEg5kBL1VW4uKAfhhZ+qgOBk=,tag:DZCSacvWbg6ozx10hCSR0w==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:lPVPQVnfqhAtmXIc/LVgePdtBNE=,iv:ITucsE4ZjOe6xVc0ZHqgmZNLftkOZ5unksiJb5dvPek=,tag:V54H9niQagx+xF5ob8hRJw==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GK7eGUCq2iDQyJTGYub1eR60DtM=,iv:RK5g1O7jPQCEQX9qyaxL6cD4nNlpw0vtmHKwg0Pyu/E=,tag:eBoKTwmd+idrvYazzkfAng==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V1vrpOEUAJDGrkUDQ05lnuV4JLJ/qtk5Ks35e8ixkUCasrjD,iv:EtPh6kAeE1NTVKsLpHAbgx2HPpTkj/tJ2RPX0j4oUfE=,tag:xeiDKdGfiaDQQhpiOWIAtQ==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWajRBeEZaYk1oYTVGSGp6
            V0J5SGkvYjJKRjlEOEJQT3hsN1E1a3hWaEFrCkszaTJLVXppZkxxbTUwNFR1YU84
            UzVhTytDN2xYR1lWZWhIQVMrcElIancKLS0tIHNkeGZkZ0xGVXBMZ3ZsQ05iTW5Q
            WmZhNWZ6R0liR3BHSG04bDZkMWpNZncKx69rwsiEnwenMZAq7k/a/N3w0MVRaW0C
            O1qLdR4BPl9PjEdmrKRbyP+6wEgUCfahXHGO22BfavM09JKQDvhAEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T07:08:44Z"
    mac: ENC[AES256_GCM,data:tGad9+FURTa1TEc/JPqc95mJv0tOQ06U5ovPchRF4WrK9+oiyMvyqT4CTlU1d6bxlyTu7Ws+0IMRe8JJ9xP3/+0E1WVGxCfGaX2utpnv+JArAMQisiI+iLcMm5Rjw9nrLtie92EF/fEyyQAiVO7ZHSngRj/4kBOzeqSt/VsVUu0=,iv:kFLKnIDHbSFT8FjhHLyNI98xjOc+XOLlWdZuy4zLlZc=,tag:bBekrawRiElPdOOFnZeQCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
