apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr
spec:
    secretTemplates:
        - name: restic-sonarr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:o6067kKplrlvnUOssJyg0TCsl+vtHFAt19N+7N2+TcwzVgsrrIHuAvNXnmCY12pQXw893iJEtzgPhl2Cgg==,iv:z5FisO+bRIGmQBLduvcYRnNa/Qmn6kcYQOs6sKJXfHw=,tag:BEyOGwte29CXAxVle6jV4w==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:bToldlG8YBWYUJZJ6DuIuJIDRtE=,iv:J4pzN8PPlBpDnyccw/t3UzF8KYs+rcKR0PiGU9HCWL4=,tag:BW65dRevOeb7H9inLwqllg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dxl/lUVcB1WvElniCnyLS+4gPfI=,iv:dtv7F7j03wAjiPH6gUnXpPJefn67pL94hFsLpy6sGy4=,tag:jIIpKr/oJVRzRL3Q14zPcA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AYGudv6EH33R+SGbQryZxidfa1CyBvFiB54f/W8DwZOZIcU/,iv:rNbs2LnH9yBiqrlPxU5s/ufsmi0agw05gkO9+us3tlI=,tag:fNBduVPGp9WKnwVVlLwUIw==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWwxbVM4Y1A0SGY2cG0v
            U3dheEtFQjZLUzYxblN2KzdMQXNhNldjbGhFCldRRjN4NVErM1dnMFNFRksxRVR0
            SWh5OU5qU2tnNGp1SHpja2tmR0JWOFkKLS0tIE4wMGFQSXFwOGE3OTFuaUUvazdq
            UHo2L2svTWVzRnorRFN5cVg4ZER3eDAKA1gqQohDf+9VA34/21ZkaF99QyEKJVek
            UTL0B36C7smnrK78pb52rVOUlCPI3FjMTLyr32rbI+b0Ew3rBcAZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T07:26:47Z"
    mac: ENC[AES256_GCM,data:3VwI7d7dG9VSOwR3GTs2DHotziT6TvzdKby3P0HzxeRV2jEUlTXbJOtaZ+VrZ8EewNOtu5A6nSx8kqACDiLsdgqWfzr0UylV5wQpib1LNcef0+kuM4SFjWXNYrFwyUb6FX7odr9I/09LowmBJAWpTF+JKppN2678SZ9ZEF28W9o=,iv:XQ+nGMmcRNha5JL41YzQZlIPMj/ulPD1vjkDQTpmW6s=,tag:81jGZpZskWegUp5SceBTjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
