apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jellyfin
spec:
    secretTemplates:
        - name: restic-jellyfin-config
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:sgvqoZWpUwgmrmNAlDy4Z+IAqdiOy5uBoelNbR/dZvw2pSvoyIZanxOFqpYibmxPZo6dKTIhZKGtrhRoXmb2,iv:HMAhtqRHdwYCAy0+RnR25CMtRAjCIuOFLMj+vpma00c=,tag:9NIyEIZR+FdLFeVEUSWcaQ==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:GYgfqLfjOkMC07wCXnrEwQCOZlI=,iv:njkzg5y5uhYHDCMo4WkHxWMTxKWHSg2jEdTdxzDUL44=,tag:xx4xGhj3kLfhLeF7LbH9iA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/rea2vDKO4icbS21pxCtsWbhfzA=,iv:z7TAfWfoAwuyzMH6QxdiSfJ1Z2M+SN6AFX8w38qOvxU=,tag:ViJgED+gTpI+z1IuB2DHSA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J5Qzk3fjUg1fj/pI4ZQzWLECpkKOi+30mAD/qMEopIKPrZmM,iv:N5AkCfNYa/EaSmofNClPcHO8zP2y6KRThfS2U2z3Z/w=,tag:cVlP+nkq6nuTDepX/0klzw==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobHlITm9LbUJtc1JhTXBI
            TWcrRnNJcGZock5SbWwzME1tN2Z1VlYwTmtZCkVNK1hKSHRuSWp5d04rUkdFZklF
            TE9JaTVPZUZqZGlONVhSTUJ1UlhBOGMKLS0tIFFhL3IyQi9wQ0l2aXN0OGJwSmZK
            c29Kb09BYlZuQ2FvN1cvb3hCK0hsSGsK78irrLm4o584mossOYvvDzinhz7MDOuG
            wb8xjUwxphELpAmrrZ4F1cF65EtSEIg9/ZeDPu2W0QN2Eitm9PAlZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:47:32Z"
    mac: ENC[AES256_GCM,data:ZsR2Fo9vofDph2b5t01lGiCWPnKEmqv2IaoplhPrd8mcjhyqVCZOvM/GoWrE1LIjjYTS33wc5+bmVPVvklRz7pTM8IDnahNpavK54Wv53Hoo76e8EM+3I0UtkgAPhtQsF3AJ80NiliG91Vg4nOn+1kkB8Qf1g/j6KM68YjA52zc=,iv:IPDryp+7Z98BlBM+WUdNUeQdKg+9ObmRp0O22uINd1w=,tag:z4PwfdFhhLHK3NFGukaqKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
