apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jellyfin
spec:
    secretTemplates:
        - name: restic-jellyfin
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:mzXLIPlw1Pzskes00pD1GJrLVik9rw0goIj3pEVrp/ZCpJzLpxEQGYRMXq3CX6py6U8Mn/FJLDpXdzgNQxyr,iv:zvSDpZ03Fd1qdlA4YcgH8EhM2fFbuRYbcZp93vYS6Yk=,tag:9Pq1tEmx+j4b/SNkiJES7g==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:bYuTR6iOs6SOFLGHk2vC2SwGE7A=,iv:TeCuGzuhhfkXnmmMj5098EKkjYnovDBCqXund1BAt54=,tag:okahRXZ92e2pVUEHFqCbxA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:M+GfOEU92td+OUH8EWJSc3LinT4=,iv:IKaLbYvd7321ENFp1s6PXZLIL3tvVctkVhOTHqQTwzI=,tag:rY8A1CDE908pw31eWV41fA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5mCbDbstaBQr79Uap6Xk/ZXe1Dkkw11Ja78rBzfmeA7as7/c,iv:vidHlt1AWQNfcPoOXht6QBphmxe57UMvZvdOMFcHseo=,tag:sfZ75A27UW2U+8/dUQ20hA==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VDJSWWc0ZDhsdllRWUVr
            bUhkWnlQTmVLQlhKd2VmQ2V3SXo1TC9nRVc4CmQvSTkxVUg2eEVBS1hkWlZQYm5u
            ci9jbE1PQUduYW9vb1pkVy9URHdyNk0KLS0tIGhYQVoreDVxcHFycGFMd2lsdnp1
            alFyNWZUZThRZy9qTHFZRWVtUzV0dWMK1J17+KCJ8+UMKfYTXsBgRlMlsjLVz+MZ
            U/rFZbT5u2+hxMQEu960khU7ir5tj0PZ5eaBBZ3Xltgbjj7Vz8v2LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T09:26:11Z"
    mac: ENC[AES256_GCM,data:bpaXWK9TuXnAHkrZjud0kV9V496oH3ebmvudjTKLYtLiTmhg34m4rAO0fRiobKTiVQ1BWyByfmIVDZOqZcPtkvqVS561Htkswwi89/4sRPCsmb0GCzuEWSlnxqP6WAtha3+W7wKqpdLjAU6UzPp+gV2VfL4DrnZQFWwFDcT01Q4=,iv:59dV4lZTSM/VQ4rxlmySY5Wj97wvcWnFKSvoKeZtTIQ=,tag:tb7BxgzEO49TFJ7+FtD2eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
