---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app APP_NAME
  namespace: flux-system
spec:
  targetNamespace: NAMESPACE
  dependsOn:
    - name: cluster-secrets
    - name: sops-secrets-operator
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/home-lab/apps/NAMESPACE/APP_NAME/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
