apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr
spec:
    secretTemplates:
        - name: restic-prowlarr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:eq6MCS9XxWSSzK40FJvkkX3MrboFXDrzrgNVwelShHBt6OTuoQo9UdGQENvW0tlPaFQWgVWWQEcrcHirtlMt,iv:gBSR6RAfL1h3YGIb5kKP5Wlq7t7W0WmQV3sfCfXH6Ek=,tag:QyAnqSn1rd5Ks8y7qJzlIQ==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:zMl+QX7ntrcMBHyhgxkv+Sjt07M=,iv:BlagUNqn1dqGZQfsbOiRqTRTYBdcdwQ/y6oDIk/4cR0=,tag:RL4m9Vria0D0g4HkRWGOmg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Uko1ZIwL74sSxKrxuVevbNsOxzA=,iv:JThnhWIc8ul3EJwTPj9CMHw2vwGqJIwP/ObCNwJB2LY=,tag:FZ6vypzzjmh6IaqcBe4NUw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0ncHGMj58mf7Di19t/JPBkcHsBnR9xCTx0ebXrKQIRcyC3Fi,iv:Eyth1jWJYv/pnwxwfLqe1W2a3AeQfjsVHxesOvtUfzo=,tag:+pddVBgkCZwmfp2nC5uGUA==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRTZtUGNQQkFFRzBWOXI2
            TTlSODN1Z01yVUd0OGZQdjE0TEJ6emtyRHpFCjdCUUhROStWQ1psTE9zeUpwMjFp
            dkZ0T0hYWjEzZnpXUmVhaVFwTEs3RkEKLS0tIDdWb3Fjb09wL214bDBuQXVuZEwz
            a0xaam5Mai9vbGJvOWY5WmROQlM5RHcKa9j97XmFibd0Ea6Yy29fwSXf+XczPn8G
            3FXQPFk4sx0t7DbEnKFIPIjpbBR7dMq/jA13ruq7jqKyTSW98VUbMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T05:39:57Z"
    mac: ENC[AES256_GCM,data:E0oEQhois92PMbyjCsLNyYpXfy2MVeizF2XDqUwuLJcIkk+yoBCJo6PpF8ucK7IkFsP3VYDXvDg/aas8SgiU+6VcIMk0kbYqZRE+X8wG72NE1LmmAP8aaCR6cuwMHiQyrNVKPl2RFc46wEciknKly+1v64Rf8ciAj3ViUxWW8OY=,iv:xNYJ3W7P4KsCj5q4YVfqO2F3KlYlHi1bysn5yBfyfxc=,tag:acbvSMWTA/yh/f1PcCvy8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
