apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: requestrr
spec:
    secretTemplates:
        - name: restic-requestrr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:cqrapytZvNtGSKA4+zxiHa2TXRc/t+yS5OFgplUDtnbg7CY2F2SsgcuLNN//g9/Uhdkj+882JTI9B8B+Xsfm4g==,iv:lTAR8fkJZo7JrsYYlHgyDsliYLs2S/dktTN3w9ae/RI=,tag:VJFA6ZYogmLlaRzctdQIcg==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:wyB5sMF4fuymi2QpeQTFXMpSvxU=,iv:f5QKXTESeLHI4BsLyhpfxKuP5PLqJpk+qWQYCoZQZ3A=,tag:u+sjshncWP3d6+1FoaWjAQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:F4e3Y6uvsbGl2QB7da+nwOmoiWE=,iv:CO4cPiq7QuQCu/5gzrzUGMUIYD/+PPW9Vm4z3NvY6j8=,tag:WoKNPy4+enFZKRdm3QPoVA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yNRTWE2+PqEKYa+VZmYDUkpaHxyVfp822KGFm2yjtzKY31gH,iv:i29+aXLedhbvnnKzdKvaTkq5udsb3qemQZ5JsUhGNoU=,tag:jQyeNi25RDZgLq/FfZw9/A==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TFQ0Q3dwYnpaQW0vbHZW
            MldhMnpLdVc5NnE2ZHBhWkpzQ1FIZ2xMMjFZCnVpLzVmUnlDQ2lFb2JCalEvR2ZQ
            cEEwOU81ZFo0WklTS2Y3empxQ3lBN3MKLS0tIGduZWY1Snk5OTMzekpIcHZkUW9i
            RjNoSFc4dWpWaHhsVXg1UmhXc0tTMkEK2b6oDnLGOV3qjwqAu1J0OUuCTZ9btno+
            SAalAuQudpsRto3Zs+fd1/f1yle5SgA+0adacnB1MYMStb7ZNPEctQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T07:22:16Z"
    mac: ENC[AES256_GCM,data:rG4HF5p514uMSyUhYP9CVqgxo+ok9rU60VDPoNNpdI/1U1WTZZZwXQ0MKo1zcjbzhMihcwYEHKKUSwvBixSXLgV0OlC8qkvwYEkM4w1+MzHKe1yb9YUm02km4SD+QBsrvFiOOb6Zju5pUfaSK5bbh5jQI/qKu9hCCEjVH+/igVg=,iv:A9CsfknjzqacyGwzZVyYz1DpQuhOwmmSsM004KqdgBg=,tag:c3G08/ilitdK8+Nmya1yOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
