apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bazarr
spec:
    secretTemplates:
        - name: restic-bazarr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:VadsO9/FoxiLXrOl6Yp2MAvWgXYPjZSS0CJMkLwjJdV3oK1mvMd7bDrpBc3Pu5CHvvgaSN/LTfCTL/CUFg==,iv:hBU6ONbDZV23nR+r+AGF6lLAgJaWcIuRKinBKwqALcY=,tag:9gKeifcbFrjGtl7kE5nCEQ==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:pnzvbx9Uwoqjac8g44FjE3KmW1I=,iv:mMGvdZZo8fwDDHbRioVMAACitBU560tE+v4hfkwPZP4=,tag:FkT6XyJdcxYB+1wxRI37Iw==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x9kKC4N0nS/4pt8Z4+DlRrqQ0Ww=,iv:lbO/Kp6KXcveWvgpa8ZIIb2xrArWa7/jU4PpEdfj6PU=,tag:9gRPdE2+wFibDr+0fEcgrw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LqrrU5xjtDy2ZHJOmW3NqAzPkcitOfQ5oXY55ZruPVrnildM,iv:IkhoFvjp/UGd8SU5t90G7aild1laYFsZ66C9wQEPx5k=,tag:Vpeo4bSnrZvNE/FNZqm5dA==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUEY1L0lLK3A2bXdGRDZY
            djdYVktUZUZtRFRpQ284M2VNTnphaVlVSnprCmxHc1ZVK1VzazQzMHRkRmFLSE5X
            dkpVSEhIYlAwbThCOW9XdktyZmcwY1UKLS0tIGlKODhqK3hBdWpDNFhyRkx2MEFl
            NGVyZWVvTHdIY1JnNENNYzRoQ1FoVzQKZOWQcJFFskUKWjhPBDDVsDGXZEfbhk3h
            VLrgJsqteQeL79yXGRhflCEvn8LdNpmrzwG/vWyBKu1vPdZO6J4sNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T05:21:46Z"
    mac: ENC[AES256_GCM,data:aUy6EEJGwt/dqdDnJR1s9UDAyKGCg7m6uxEAp2Kq3ZBk8XXPtFwin/DTl9+4WA5IAzZ1ghNm/O7nEsctD8BnQkTbpIaipiEFqySkiNTTCEn0G2WOdEDYgZNId1AEaGFXAlqiOjt4evsnLF5LA9WKQmt+Gpf52gci40lGEDIilGw=,iv:ff+di4KMG3ndHyLbuXt28uqWpRqbtDXuSmad1rg2UfU=,tag:L96qKZQCP7o6Mc4tPFLDeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
