---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-data/ks.yaml
  
  - qbittorrent/ks.yaml
  - flaresolverr/ks.yaml
  - prowlarr/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - bazarr/ks.yaml
  - requestrr/ks.yaml
  - cleanuparr/ks.yaml
