---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - intel-gpu-resource-driver/ks.yaml
  - metrics-server/ks.yaml
  - sops-secrets-operator/ks.yaml
  - snapshot-controller/ks.yaml
