---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server/ks.yaml
  - node-feature-discovery/ks.yaml
  - sops-secrets-operator/ks.yaml
  - snapshot-controller/ks.yaml
