apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radarr
spec:
    secretTemplates:
        - name: restic-radarr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:JE6QnQWuo4QuPyrIe/iH5WI9zyT72J3cSyHVm1schcVWBVXfiqG5OcIqU2NBVYuthUVX2i61qH361cS0lA==,iv:FCoUEpHJe70dX52nnsj8B+F+o+NmeA/C3MfKIWPYRRY=,tag:yo01U8jZIKdYymjNL/Hjag==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:k1UIW9vTKPUW15kpNqOhBUryifM=,iv:214tN1er1kFhZGxZMUNU1kBPUqoqh9oYiNjj0BQ4ZnU=,tag:6d4HCbycnxaorVrMc/pQcA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:asnH+5HErUBnaoPQJKNKRiGIlw0=,iv:jJJOBF9q2BVAQl6MX7S56slLf846/ATekpGhyTQvqpU=,tag:loLJkptMWyrxOcJd0xm8Rw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P6LPK3wL4CRlJ/iqjF4IBswweg+uunmZKXylrNOiE/Cr3nMC,iv:zI5B8kPixRIKrbotVix4QnnvSmxtmXkiF30SnvBuLUg=,tag:fA+cFZLzDbCv/4wZ1G7vKg==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSzBWY0d3SzhSZTRVU2xO
            ZWlBZ1ZZKzFPUFdQNDZWNmpYcG9oQkJjVFVNCmJ0bno4c3VLcGk0QmFtUnBHTzE1
            Tno4N3RHSVVOUkxZQ09yWFk5U2Z3WlEKLS0tIE9Qams0QzlBdlZXU1cvRFZJaHRu
            VnJhS0NlU1JYREE3R29GZE9hZHZpVU0KKUODXtzOCMuWPY7Q7rdpxv7X4w8/lXKs
            58auEepZCQ28DAQTfhyk5VmaeVKxsHUtSmY/qwvozh2+xqxLwfCbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T07:18:50Z"
    mac: ENC[AES256_GCM,data:kTOcMqGFpP2PSXoIzxXdnpxhdADx8VVvot3zvgcmxQQxpWFRyuKijpXQhXS5iyzEQffQWPspTLGbOUlSWKiW8Zq8ajSnZLBsRXjH8+Imb0uBN5sB3j3vs4LCN0946xN17VT2gtiH12I+QxSfWJ6rYYFiVO0q9cpN5fgZiqethmU=,iv:+28LFqoP4RN7mrLWi5GK37n/TFG1+iTeSavukccGA2Y=,tag:3ERvA/UWKAptHYOZAEwJkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
