apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cleanuparr
spec:
    secretTemplates:
        - name: cleanuparr-config
          stringData:
            SONARR__INSTANCES__0__APIKEY: ENC[AES256_GCM,data:2S4TpD62EUeAnGjZgFFDbgd414r0zVSRaZdmXRFLKVY=,iv:/Y5/bhQZWexq0Qp+VPXzM22aLrjRQrKkllRYUzx+eZE=,tag:ujdjrO7DaFEznKWrHlw08g==,type:str]
            RADARR__INSTANCES__0__APIKEY: ENC[AES256_GCM,data:7WMU07ZXTpJATrTKaFymPpRW2jqlfz+JHV22gkY1t7I=,iv:AfpMSIcBFF6ZSpqzTwnUJcYGTbOfJjNeXLIpgvPH1s4=,tag:RD5Q4TbYP8I+HHfeGtxKZA==,type:str]
        - name: restic-cleanuparr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:zYDIq7TqWp1EZaP422towr5YQoJm6wH5Qj7jI0AxcIOrNHFJvKw8/UAqP0PFrlyLtEu5pG+zhRQVJGhfWJkGLfE=,iv:OYgGP7LcKDCwqPKGdBaaCiIAFYi7ZjbxayBOwiYeoAs=,tag:qCsYiGvWRY0+/lwKyUwanA==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:RNP9HPrfN9XCgbJlxXIAMAl8mO0=,iv:7Ht6cmbeMmgHX2q3RBP60NBlSjI+1rf2ESPYXIH9wuo=,tag:tkVR1SINdUGHaNuRarbpGw==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k+leXwbQnyE+KbIDy4JMwpqraZE=,iv:YaR2YIlEUgq8Y3RHh4ID1Wa/pMIB61ALPcg7wdibHiQ=,tag:weiNu47kySNImi3TWKStLA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rk2IlqObY6t7KgN9WXlQ0hcLuHMsgH0tpeelxub0t2sfJ51l,iv:/CZx9Y9NTKCluBvECajtUmHQIPiTLgYKQYYTg0gaQjA=,tag:bEcvTirJPh2Z8AbgG3MJHg==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRDJYVlBDN2FxZ295MUx0
            bGZkWi83T2hDM3JrTDZtQ3c4SjZlcldvMXpNCnY0UUJCV1FLaGhDM1lJYVkrSWFG
            Z3N4eEVEaXZpeSs5Y1Y3MzB0T3NnNk0KLS0tIDNkb1QwSUltMHM4VnIxTzVJWFBn
            ZzFXb3pHRjZaT05pMTliN3kwOEtHcDAKWLoSsrHQP7A+iFr8wofQuoBBwTYMDcaV
            ilgG0ETRzLF/h8LxdSuJ/lSY0q5rDZ/N3F6XicOpfv8XbxU/uwuoqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T05:38:00Z"
    mac: ENC[AES256_GCM,data:42daP6qkSruHNM07M0esRMo9IapLiWRb32LWNY/p7QX2fPoxq0bq3mMpKGYsPJCJzwKb7xUusdIMefySWgHBG6n5mbd0wg8L4Ex68DSRfO4SBCMpmm3WaJOx55K4xXGvYXy3o3l1mhoAgQqjZWF4F0uaBSSLL7i4K8eCtlt1qBA=,iv:IFW9jYP+z62H3bnNphPZFe3NF3mb5BtujtUKtX5GO64=,tag:w94H1FKGbywNntcHNFDG7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
