apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mealie
spec:
    secretTemplates:
        - name: restic-mealie
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:7nyDgVfCr9XOGAhzn3vMyUhFDXvlMOfWZ4eLGLYZXL1IxGaN6BNa+/tfoo2Anf0F1l0KTGp8VWBjK7Q=,iv:OBs863lpQl0Jlh6Y1PZjmOhtXrClX0nf1AtUoOsHWro=,tag:6QGNCnGvzYJc18W2xrN8Eg==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:Dl2UfPSn/z7nkFRAWFsDWqpkXPQ=,iv:YkBSeXkkySBCqNNvChNYwltToC23bRCyd8POsdpiTrY=,tag:4L1w/L7W1HejYWIO3QtNqA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5ucFT37KJygf1+aObUePO1uLX2U=,iv:vljZ5YzPGRgLupWAlQ4aEBzpQNNvO+L9vuzL63guizY=,tag:qvAOQpHOWJecN0fsPv7fKw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RbGh4mXuGfUbBbImgPmWec6efhUKYGxOHvv5pnXlLze1wjCr,iv:zPzyRUybmG3YKnxXFjd7LJuiiwW0aHWExvKuYpHJxWA=,tag:sFGj7gbeY7cPY0y2VYWL3w==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWTdEbTNURmhDQXhqNU14
            czZ4LzNpNUVYTWYwL2RoWnRqcWVhdmtBVFY4CjA0OFBDcGp4ZitpcUlXdnhaaGNt
            SjJsOXBKNzhsUjJ1QzcwVnhSWG5xa2MKLS0tIFFKYUpJVWZ2a2FrZi9iNSttc3pY
            REtRbXpRSmh0RWx6N1VvL1haRExwWFEKrlBldKEaakiyYzxHCcGuRo3RqMtm4wde
            0kB6Lm4DhALo6qnCkxbfnNeoHiTlu1SZYGXXNkqiMiR1tdfxNQxs5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T14:43:22Z"
    mac: ENC[AES256_GCM,data:Lxn6mDx07Rp+mXyI0B6AGOo4Xd1/DDeH2LP+yLlaYiIO25Hx8oWJu436TI7nGwGOJQP5ncIsr9IzFtmQp4pqewM0O7tCUna8o99X0gQArW6twXXBs/f/pyesjPLY0w5NPRxL9NWehxX9Bbe1voI8jpkSY7PtfT2kRB9koyJTS6I=,iv:vFN/U68BD4kM4OB7cKmGwKzxuFWmHgESd3ojQJwewJ0=,tag:n9WLWqk6QSS6hntWE+Zq0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
