apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dispatcharr
spec:
    secretTemplates:
        - name: restic-dispatcharr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:VkGFLbvEg7VUUqoDvbL0Z7tE+LbvecDRvzMvMFTKB7h5BGyqw9638bNE0yaKnhzE47vXY340TogYClqIwPQdvZY6,iv:a0Y/l7zNJr7dJ04Y+/YnF1c7yg8zVQdgVixxLvWi1yc=,tag:7PrdDgritJL/p+LW225lww==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:Ol4HVWulaRssfqJaQlB9ny/scBQ=,iv:wZJUjVy3+pj6O3ttWC5qLj/BIbIXaI7dcCfnrcoOFdc=,tag:wYK53duiQe0j1H3QEEvBkg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/1HRspMUdA/zpXmxlCfD0CzwNVY=,iv:FXz4Tm8r/020ejM8dAGg++m64ZVjR3xEF/Y+lPFAWbU=,tag:fdb0K1KXkU9CP2M7S4/75g==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1iI1aE1V5jR2kfIJcttTEa1BZwdC/5KM3A5OylAifjdhqZSR,iv:jHaPF0U1nuqRU4xcAjnU29F4ZgNJWw+M5EGI91Qwk8I=,tag:Hp+f0lZ9DoK9yCwTkbWYgw==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSUJOTC80Qkd6cDhQaFdQ
            ZHpNN3lpSi9VejBwVlZCTTF4bTljY29Hc0ZzCmhUQnBqdVh5SjBPWTd1YlpUVll1
            OGxzVHhSTUg5bWlYNUJPam8xN2RtdGcKLS0tIEFKbzJSaVM4VGppWXhIWE9Xeno2
            NmZtY1U1c2FqM3NOZ2dwUEF1TTd2V2MK61ISWx2o64TyWCS1jQMwMk5ryDawrtzm
            tPnKfn251l4oMzBnNMotIKlww9QGg7Ui60ADIPN2evvw0DQqmm5GEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T06:14:23Z"
    mac: ENC[AES256_GCM,data:mPjHNd+WLGrxg1bxBlsMd9wA51iyerF+JqTiM9d1q80q57ILBbe2J/pmsw4IIOAMuuJffDlK+BtEOol4oIbzvRLoJ9aYd5rX3BzQh3xPXtvgGpnUrQEQGfGhIe1G+smeFU317Dgq+1SaZRcGTxPtzvvn8RkLfA4fdUBaguchrYg=,iv:8R/wkkSffGsMbgSnvZFnL7Hfnc4g77S0gAIAhBRkFKE=,tag:UXZOaspvJMwoeyN4CpMKZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
