apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shelfmark
spec:
    secretTemplates:
        - name: restic-shelfmark
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:p4kt8Zj8DPwn/uJ8WjYDxBD6yMCqXEPtai/0gb8LpZz8P6spgb0LWR87+AJTfWlPBxIWPWw4w26Q,iv:/QImGKMpk7CSuaTEyac/9W1GHoPGB/Ccl1CISgYzIBQ=,tag:2Qd4czydQR+JprMQBGWwBQ==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:FlbqiJVSCL7w85M4zirVIOWI0ro=,iv:IjlOG/OAK2VFhKBqhlIiyrEZdr7VBzpSGC+jvrCIiVA=,tag:jPavvGWCcJxgob/BfAgHLQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5963lZUrQ1lct2DFq2zDAeF9afo=,iv:qBS7xTteTRf/ruTDDVyEJpoObS093yvcTxmZozqJTOA=,tag:s7jnfZM/rTwPp9RXI0d1Uw==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TVhGjAwIjdd1GVpe9EFArCYSZU6DviogeM8u2njboNvVBlb5,iv:ATXGOjkbp0rbg3PJboCHM4cptYOPBZMe1Vuj9D7HcxI=,tag:uk6oNSnv5fDBMKPDMwzwbA==,type:str]
        - name: shelfmark
          stringData:
            PROWLARR_API_KEY: ENC[AES256_GCM,data:ydTrbdfLZN7194Q+OwE6MR7prksORvJ2iiR3/h8xp1A=,iv:dmwwJNFrp4/ry+U4L0Cx19eHl8p3gJyj9i/dE58X1So=,tag:xRRvFPu9GDnNZPND1+SM4Q==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS1ZTRG02VVlLekUrc0Q2
            bHQwUnI0YU1EY2ZPWndESVAvMDFwa3A1cXpVCmI0Y1FRcFdOS2FJcFFLZmpJY1g4
            N05UeVVYMlA1VWhGK3BmMzJtWk1yQXMKLS0tIEZBWUpHU1ExMG4rK0E5M3NNNmlX
            U0o1cVlJRTRGdktML2pvL2FFT29YSG8KeOZ29tnpeURwxPUlA5KlA5Txgzyhzp3E
            nMHiJDd8mwG48nfsAr1humILCembDXJGzIMEEVyCYkqEFs9fR3U69A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T05:15:51Z"
    mac: ENC[AES256_GCM,data:oreINKjb/6X590FuPi9tu4HIm7Q7TH1jrUXdDVF2XJ/A+kaw+QcRFaF/UqLamouOfBLhvbZAs0sefNLcUv+q1bJDp7JpJvsgUXJA2kfiuZwXh5avbzrI+3Do3dfyJ0aGaU2eVD853Pqj+8fCJ1yQ2srIFfCe0IJORUILFLEVr7g=,iv:Qk6VL/iSioOOU+OlX1kjzh9Oew04vwJLG0kf534z2wc=,tag:Mn2Nz8qEhyz9mGfIyzPfGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
