apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: watchstate
spec:
    secretTemplates:
        - name: restic-watchstate-config
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:SW5ZZeRHt9gaaE9V4LsnpahcGgm4RiTEXZI9ph1f5ZKk0XLRCN3rfDIz0VlKvk/esZwCYtYjlLIMwzPv396AGP8=,iv:GCQLk4cwwSMV/iCrxJS8JEgDNJ9/YYM0NcSqzHYSutM=,tag:Kwj8SqH1luCAkCBkJ5JtzA==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:eQnMqzWe0eK7H5pFy4g5qHmXmpY=,iv:U0JWBlDUrtjnPCIvf8TuYULAA+Z7wfF8BhOKWWYJmr0=,tag:5p6z/mautc/e+yMskN55wQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vpqP7AcaRdoDJFZZkMnZMpULvSw=,iv:ZAEWlZxRPMUSwVg5AUZ94gGfMw3Q+28KidckRHmcgR0=,tag:ByFemGbs1F0va1FL+EKtcA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:i7R5CerSw3ex0oI0WWCVwY6qo8pmsCnPAEWKXnvfTne7YYjJ,iv:BZy08PClhAptts4d1kDbMPpUjxQvd9BvqOCW+2T90i8=,tag:oU4kB0kWNfkVj5NVmdp6Ng==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjF4R3pTVmhwMWc4Um5k
            YTRFb0V5bTBJRTBaSS93TnBpZzNxOGdBNTFRCnJmY29YYTkrbkVsdDduQ3RNdjhS
            TUt4ejIwYWdPUFdKamtqcHNrdE0zZU0KLS0tIDZNSERPM2txNFJ6UDVYQXRwbnpC
            NjFTVDhFQnJESXVHeEsxSE5COHB0Y1EK7pRctgSYvOg75GgJ9G0Lvmr6TtWGAgTZ
            hQpGUfUT0UUZ2oi6qJF0GpHZTSJ7gGDCWOBi8IuaXAaYc8QbWvvNPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:49:11Z"
    mac: ENC[AES256_GCM,data:KCddW5ySD+zx6Nf7YShB6nss8DuwPJ2jZxo0cseeoHpPfyzS3GaspeT0yyvOZKpIAf638QzFp9uqh7y7H7heE5i/A7ZpT/nVSKmaT2DwVArquMA8ImUF1ppHVo8lLX4vG6+qqj5SLeQIoK21nXWfzu+xB5xQ9oTgNsLLjEih8jU=,iv:34YZAn+lOgysTatETys/Ip/iTyHCVesyL/wF9Pbd0Ak=,tag:Ws6ZGyOoBInLZ6xqyrCNgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
