apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: watchstate
spec:
    secretTemplates:
        - name: restic-watchstate
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:2gYRJ3gEiJZ0EKNslkpyU2z2hVpjtK1tGkbTto9GHJXlDhHN+UD1Uc9689BBsKPOuqM9GNfahyLz2pW16l5MTpU=,iv:uUkOgVp6SEEYe/BmqJZK2r+F4HzAZBfFa5BCVwQHaDU=,tag:ttRzC8uN7MgJP7kcnKp2mA==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:KKDU1motXyPD9y22dLkIY4iR9E4=,iv:0Zb5luaHH4/rz1+aHk1vVVeP40aahBwhlQxn2bEuGu8=,tag:YkqrAbwqd3K9a+5LsYy5IQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:d/5FMW4mQ8LsP9cgZ50mKXVtbOg=,iv:BNmam1qkUCG5+n3Ffz3ffzzQP3PE1GYJlMY3Zlhu40c=,tag:lqT5YINDjRyFVLOrxTCn8Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JXPtG0LZ8CDahMSSkan5x5VWdtXWKAI0uZJHtst63YUvkIZj,iv:jBakbBJoWplZGJJmd5aIRXEEl1TNACQ394oouHKfIa4=,tag:pDW4yVweqbFHmZFVslKmug==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUU5lQjRuYmVXbkFLU2Mv
            SlY2NkNGeUtFWTZPZ0NGc2NMVWdRSCtqWm1nCklvU25CTUFIelRIOVVLQmhTSVI3
            ZkQxaGNNWGRtUkd0NkZVSGNsMFRGRXMKLS0tIHV4TTZSckVhaXhJWE9yYmVHMStO
            RGNIbGFlYmQ5UkZMSHpRK0lmL1BzYncKZtZYrkb2pB5dqnwKhc6RxRrszd3Z0onv
            00SwwUXlE0jieTGTAMuiv2LS4fMIt0uePkp6JEumzw5lziksrADT2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T08:48:47Z"
    mac: ENC[AES256_GCM,data:O3u8oJyx6pDX6Thbpbzu3It3Fugrx3SxyFKUfammobp/VxgtCuAe14ZTRvSYMSozrLhEHKBNJ3VZnjbw6zV/DICo5yXw4vxcX47uZlTIXwuDFBm9z57sb047mAwGya59CecdA0tQkXC/1KnXkqbb5IQKCWlN9qQB6EPkCg3lg+Q=,iv:pZXbM9Zs5YpDd6ef9JbsdFEbA0N5tDF7KOdjEnekGH4=,tag:X+R6toKm+akI8jU882j9yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
