apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: home-assistant
spec:
    secretTemplates:
        - name: restic-home-assistant
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:45qvzVsMfrLcbSvLfGdILG4TDsYl8e7Jv1v5aPKaGPugHbVG2/mdvnWxd7Aw13jCzuWZDJ0Q8EE1bP2goN9tJ6U83KLE,iv:yCxxZgWkn8xoaCNjeY0uIpJHgsGou3K6ysLi5P1Pzdk=,tag:tn2io2m1DPJtkvcY92j1Sw==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:xmnYAF2mwV2QecEWPwdoNMxSSUk=,iv:mqOl+jsBaFUUzdkAXN+AcPc4Of3ViLVeQ0KGmSUkzZI=,tag:RaYS4jI47oQ9fX03Aebg/w==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EUF3hzCqkOgaTVGUB402nFDUO4s=,iv:IEd5EXbp2ia+xCCNWevCnhTSv5jlCAkXUa+Gd7DkZjQ=,tag:oPErd/BwWlWOzWmUo/VBqg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ab+FNfCLhXNb5scucJWfILjMxGFdFrxwH9cV0k/84qLs+TBy,iv:PrBLGFiVX9CvGGO55N2sy4581o+RhPHX+l+beGd65o8=,tag:B7s5uT8U2m6eVZSKI/xLZg==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV2h1TVRzbEZlU0NGOGJC
            NE9SV0s1Q1Z6OVNzeXhwS0lvL0MyaFNtaDFzCm4zMDBwQW0rREgxYUU3N0R5QjJ4
            NWd2TVd2UUhwVllDc0dEQWpTNUlURmcKLS0tIDcwcjZZbnRvQkIxN2pGME9CYTRs
            VDFDOXBvWUthSlYyNytRVEk2Qnp5UGsKK+C1MpLOPGCXam9lLQijWmm5XeYNTZdh
            5L+lDQfn9qETi1oyFuQek3eV9x5AIpysbtoIANoKiAjPgDxfkHMK0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T08:31:40Z"
    mac: ENC[AES256_GCM,data:lnPY/t4WBdGdQZc9SSuiiANgNMnkr8jyVaXj2KGh8N6onCrva1cpxgODC7f6CblLl6jOcLXlNvyKWqivK7wXOfQxwI2wReA9x0KNYNDa3mI0F9cZicjIBsae1D5Lyrw0R6I960dbV4p8YEpqCZxIyywoWmHODmjltUeIiMjdGIY=,iv:sjg7IE4HbGljR5O8LLrAfAFr+YP1B46kxvJjurdRBZs=,tag:OhtGTFPNiVfuXjkJ+amk+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
