---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-data/ks.yaml

  - dispatcharr/ks.yaml
  - jellyfin/ks.yaml
  - plex/ks.yaml
  - calibre/ks.yaml
  - watchstate/ks.yaml
