---
# yaml-language-server: disable-all
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: ${VOLSYNC_RESTORE_TRIGGER:=restore-once}
  restic:
    repository: restic-${APP}
    copyMethod: ${VOLSYNC_COPYMETHOD:=Snapshot}
    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    storageClassName: ${VOLSYNC_STORAGECLASS:=local-hostpath}
    accessModes:
      - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
